apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nyetcooking-redirect
  namespace: blog
  annotations:
    cert-manager.io/cluster-issuer: prod-issuer
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: https://nyetcook.ing/$2
  labels:
    name: nyetcooking-redirect
spec:
  ingressClassName: nginx
  rules:
  - host: worstwizard.online
    http:
      paths:
      - path: /nyetcooking(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: nyetcooking
            port:
              number: 5000
  tls:
  - hosts:
    - worstwizard.online
    secretName: big-prod-tls
