apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nyetcooking-redirect
  namespace: blog
  annotations:
    cert-manager.io/cluster-issuer: prod-issuer
    nginx.ingress.kubernetes.io/permanent-redirect: https://nyetcook.ing
  labels:
    name: nyetcooking-redirect
spec:
  ingressClassName: nginx
  rules:
  - host: worstwizard.online
    http:
      paths:
      - backend:
          service:
            name: nyetcooking
            port:
              number: 5000
        path: /nyetcooking
        pathType: Prefix
  tls:
  - hosts:
    - worstwizard.online
    secretName: big-prod-tls
